name: Print Secret Value

on: 
  workflow_call:
    inputs:
      secret_name:
        description: 'The name of the secret to print'
        required: true
        type: string
      additional_message:
        description: 'An additional message to print'
        required: true
        type: string

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret value and additional message
        run: |
          ls -l
          SECRET_VALUE="${{ secrets[inputs.secret_name] }}"
          echo "The value of the secret is: $SECRET_VALUE"
          echo "Additional message: ${{ inputs.additional_message }}"
